### ISSUE TITLE
`codchi init` command causes error on Windows due to incorrect store.tar.gz location

### ISSUE THREAD

**Issue by g4yamanaka** [aformatik/codchi#26]
### Issue Description:

**Overview:**
Running the `codchi init` command on a Windows environment caused a panic. The issue was due to `store.tar.gz` being located in a different path than expected.

**Environment:**
- OS: Windows 11 Professional (version 10.0.22631, 64-bit)
- Codchi Version: 0.2.2

**Error Log:**
```
Panic occurred in file 'src/platform/mod.rs' at line 34

Failed initializing Driver.: "wsl.exe" "--import" "codchistore" "C:\Users\username\AppData\Local\codchi\store" "C:\Users\username\AppData\Local\Temp\codchi\store.tar.gz" "--version" "2" failed with exit status ExitStatus(ExitStatus(4294967295)). Stderr:
```

**Cause:**
The error was caused by `store.tar.gz` being located at the following path instead of the expected one:
```
C:\Program Files\WindowsApps\Codchi_0.2.2.0_x64__zhe5fvwpe5y5t\VFS\Common AppData\codchi
```

**Steps to Reproduce:**
1. Install `codchi` on a Windows environment.
2. Run the `codchi init` command.
3. The error log as shown above is produced.

**Resolution:**
The issue was resolved by pointing to the correct location of `store.tar.gz`.

**Additional Information:**
report:
```
name = "codchi"
operating_system = "Windows 10.0.22631 (Windows 11 Professional) [64-bit]"
crate_version = "0.2.2"
explanation = """
Panic occurred in file 'src/platform/mod.rs' at line 34
"""
cause = '''
Failed initializing Driver.: "wsl.exe" "--import" "codchistore" "C:\\Users\\username\\AppData\\Local\\codchi\\store" "C:\\Users\\username\\AppData\\Local\\Temp\\codchi\\store.tar.gz" "--version" "2" failed with exit status ExitStatus(ExitStatus(4294967295)). Stderr:
'''
method = "Panic"
backtrace = """

   0: 0x7ff68499b930 - <unresolved>
   1: 0x7ff6846ef64b - <unresolved>
   2: 0x7ff684725b06 - <unresolved>
   3: 0x7ff6846e3e28 - <unresolved>
   4: 0x7ff684980190 - <unresolved>
   5: 0x7fff129e257d - BaseThreadInitThunk
   6: 0x7fff13deaf28 - RtlUserThreadStart"""

```

**Comment by htngr** [comment]
Can you post the output of the following commands?

- `codchi --version`
- `codchi -vv`
