### ISSUE TITLE
Failed initial process produce invalid state

### ISSUE THREAD

**Issue by sebsgr** [aformatik/codchi#27]
If the initial process fails (e.g., due to an invalid repository URL or token), the status command does not list the code machine. I believe this is the correct behavior, but when I try to rerun the init command, Codchi encounters an error (`Code machine '...' already exists`).

Environment: 
```
codchi v0.2.1
d397ca96519512b1d117ca0c373b380006b3fc4b
```
Steps to reproduce
```
$ codchi.exe init java-ide https://oauth2:XXXXXXX@XXXXXXXX
Code forge: Gitlab
Error: Couldn't access repository. If the repository is private you need to provide the correct credentials. If it's a local repository, make sure it is checked out locally in the machine at the provided path. See <https://codchi.dev/docs/start/usage.html#creating-a-machine> on how to access private repositories.
```
```
$ codchi.exe status
┌─────────┬────────────┬──────────┐
│ Machine ┆ Status     ┆ Running? │
╞═════════╪════════════╪══════════╡
│ demo    ┆ Up to date ┆ ❌       │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ test    ┆ Up to date ┆ ❌       │
└─────────┴────────────┴──────────┘
```
`java-ide` is not listed

```
$ codchi.exe init java-ide https://oauth2:XXXXXXX@XXXXXXXX
Error: Code machine 'java-ide' already exists.
```

**Comment by htngr** [comment]
> $ codchi.exe init java-ide https://oauth2:XXXXXXX@XXXXXXXX

Btw: Please use `--token oauth2:xxx` for private repos

**Comment by sebsgr** [comment]
Thanks, but the main issue is still unsolved.

If I use invalid URLs or tokens, the process stalls while retrieving available modules. After stopping the process with CTRL+C, the same problem still occurs.

**Comment by htngr** [comment]
Should be fixed in <https://github.com/aformatik/codchi/commit/d8a0acf8b5f0cc28ffc4a136af1a4e3bd505faa3> (v0.2.3). Until then you can manually `codchi delete` and then init again. If that fails `wsl --unregister`, delete `%APPDATA%\codchi\machine\java-ide` and then init again.
