### ISSUE TITLE
Find better name for project

### ISSUE THREAD

**Issue by htngr** [aformatik/codchi#6]
Devenv or similar names are already taken by devenv.sh, devpod.sh, floxdev.com, devcontainers, jetpack.io/devbox

**Comment by sebsgr** [comment]
- DevManager
- DevAdmin
- DevAdminer

**Comment by sebsgr** [comment]
made-up words:

- devmin
-

**Comment by htngr** [comment]
DEVelopment environment mainTAINER
Dev Machines
Code Machines
Nix Machines
DevOS
